/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { FaDownload } from "react-icons/fa";
import { getDeveloperReport, getDeveloperRestaurants, getOrderFee } from "../lib/orders";
import { isSupabaseConfigured, supabase } from "../lib/supabase";

const money = (value) => `Rp${Number(value || 0).toLocaleString("id-ID")}`;
const date = (value) => new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const today = () => new Date().toISOString().slice(0, 10);

function Login() { const [email, setEmail] = useState(""), [password, setPassword] = useState(""), [error, setError] = useState(""); async function submit(e) { e.preventDefault(); const { error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError) setError("Email atau password tidak sesuai."); } return <main className="grid min-h-screen place-items-center bg-stone-100 p-4"><form onSubmit={submit} className="w-full max-w-sm rounded-lg bg-white p-7 shadow-sm"><p className="text-xs font-black text-[#8136be]">KEDAI KOTAKU</p><h1 className="mt-1 text-2xl font-black">Masuk Developer</h1><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-5 w-full rounded-lg border p-3" placeholder="Email" /><input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-3 w-full rounded-lg border p-3" placeholder="Password" />{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<button className="mt-5 w-full rounded-lg bg-[#8136be] py-3 font-bold text-white">Masuk</button></form></main>; }
function Forbidden() { return <main className="grid min-h-screen place-items-center bg-stone-100 p-4 text-center"><div><h1 className="text-2xl font-black">Akses developer diperlukan</h1><p className="mt-2 text-stone-600">Akun ini bukan akun developer platform.</p><button onClick={() => supabase.auth.signOut()} className="mt-5 font-bold text-[#8136be]">Keluar</button></div></main>; }
export default function Developer() {
  const [session, setSession] = useState(null), [ready, setReady] = useState(false), [authorized, setAuthorized] = useState(false), [orders, setOrders] = useState([]), [restaurants, setRestaurants] = useState([]), [error, setError] = useState("");
  const [restaurantId, setRestaurantId] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState("");
  useEffect(() => { if (!isSupabaseConfigured) return setReady(true); supabase.auth.getSession().then(({ data }) => { setSession(data.session); setReady(true); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => listener.subscription.unsubscribe(); }, []);
  const load = useCallback(async () => { try { const [nextOrders, nextRestaurants] = await Promise.all([getDeveloperReport({ from: from || null, to: to || null, restaurantId: restaurantId || null }), getDeveloperRestaurants()]); setOrders(nextOrders); setRestaurants(nextRestaurants); setAuthorized(true); setError(""); } catch (e) { setAuthorized(false); setError(e.message); } }, [from, restaurantId, to]);
  useEffect(() => { if (session) load(); }, [session, load]);
  const stats = useMemo(() => { const completed = orders.filter((o) => o.status === "Selesai"); const active = restaurants.filter((r) => r.status === "Aktif").length; const dayFee = completed.filter((o) => o.createdAt.slice(0, 10) === today()).reduce((sum, o) => sum + getOrderFee(o), 0); const monthFee = completed.filter((o) => o.createdAt.slice(0, 7) === today().slice(0, 7)).reduce((sum, o) => sum + getOrderFee(o), 0); return [["Total restaurant", restaurants.length], ["Restaurant aktif", active], ["Total order", orders.length], ["Order selesai", completed.length], ["Fee hari ini", money(dayFee)], ["Fee bulan ini", money(monthFee)], ["Total fee", money(completed.reduce((sum, o) => sum + getOrderFee(o), 0))]]; }, [orders, restaurants]);
  function exportExcel() { const rows = orders.map((o) => ({ Restaurant: o.restaurantName, "Nomor order": o.id, Tanggal: date(o.createdAt), Total: o.total, Status: o.status, Fee: getOrderFee(o) })); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, XLSX.utils.json_to_sheet(rows), "Laporan developer"); XLSX.writeFile(book, `laporan-developer-${today()}.xlsx`); }
  if (!ready) return null; if (!isSupabaseConfigured) return <main className="grid min-h-screen place-items-center p-4 text-center">Supabase belum dikonfigurasi.</main>; if (!session) return <Login />; if (!authorized && !error) return <main className="grid min-h-screen place-items-center">Memuat dashboard developer...</main>; if (!authorized) return <Forbidden />;
  return <main className="min-h-screen bg-stone-100"><header className="bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between p-4"><b>Kedai KotaKu · Developer Platform</b><button onClick={() => supabase.auth.signOut()} className="text-sm font-bold text-[#8136be]">Keluar</button></div></header><div className="mx-auto max-w-7xl p-4"><h1 className="text-2xl font-black">Dashboard Platform</h1><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([label, value]) => <div key={label} className="rounded-lg border bg-white p-4"><p className="text-sm text-stone-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>)}</div><section className="mt-7 rounded-lg border bg-white p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Laporan order</h2><p className="text-sm text-stone-500">Hanya order dan fee platform; data pelanggan tidak ditampilkan.</p></div><button onClick={exportExcel} className="rounded-lg bg-[#8136be] px-4 py-2 text-sm font-bold text-white"><FaDownload className="mr-2 inline" />Export Excel</button></div><div className="mt-4 flex flex-wrap gap-2"><select value={restaurantId} onChange={(e) => setRestaurantId(e.target.value)} className="rounded-lg border p-2"><option value="">Semua restaurant</option>{restaurants.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</select><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="rounded-lg border p-2" /><input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="rounded-lg border p-2" /></div><div className="mt-4 overflow-x-auto"><table className="min-w-[680px] w-full text-left text-sm"><thead className="border-b text-stone-500"><tr>{["Restaurant", "Nomor", "Tanggal", "Total", "Status", "Fee"].map((h) => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{orders.map((o) => <tr key={o.databaseId} className="border-b"><td className="p-3 font-bold">{o.restaurantName}</td><td className="p-3">{o.id}</td><td className="p-3">{date(o.createdAt)}</td><td className="p-3">{money(o.total)}</td><td className="p-3">{o.status}</td><td className="p-3">{money(getOrderFee(o))}</td></tr>)}</tbody></table></div></section><section className="mt-7 rounded-lg border bg-white p-4"><h2 className="text-xl font-black">Restaurant</h2><div className="mt-4 overflow-x-auto"><table className="min-w-[620px] w-full text-left text-sm"><thead className="border-b text-stone-500"><tr>{["Nama", "Owner", "Order selesai", "Fee", "Status"].map((h) => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{restaurants.map((r) => <tr key={r.id} className="border-b"><td className="p-3 font-bold">{r.name}</td><td className="p-3">{r.owner_name || "—"}</td><td className="p-3">{r.completed_orders}</td><td className="p-3">{money(r.total_fee)}</td><td className="p-3">{r.status}</td></tr>)}</tbody></table></div></section></div></main>;
}
